// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// GENERATED by flutter_rust_bridge — DO NOT EDIT

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'dto.freezed.dart';

class AppInitConfig {
  final String? stateDir;
  final String? configDir;

  const AppInitConfig({this.stateDir, this.configDir});

  @override
  int get hashCode => stateDir.hashCode ^ configDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppInitConfig &&
          runtimeType == other.runtimeType &&
          stateDir == other.stateDir &&
          configDir == other.configDir;
}

class AttachmentMeta {
  final String name;
  final BigInt sizeBytes;

  const AttachmentMeta({required this.name, required this.sizeBytes});

  @override
  int get hashCode => name.hashCode ^ sizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AttachmentMeta &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          sizeBytes == other.sizeBytes;
}

class ClipboardEvent {
  final int remainingSecs;
  final bool cleared;

  const ClipboardEvent({required this.remainingSecs, required this.cleared});

  @override
  int get hashCode => remainingSecs.hashCode ^ cleared.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClipboardEvent &&
          runtimeType == other.runtimeType &&
          remainingSecs == other.remainingSecs &&
          cleared == other.cleared;
}

@freezed
sealed class CopyField with _$CopyField {
  const CopyField._();

  const factory CopyField.username() = CopyField_Username;
  const factory CopyField.password() = CopyField_Password;
  const factory CopyField.totpCode() = CopyField_TotpCode;
  const factory CopyField.customField(String field0) = CopyField_CustomField;
}

class CustomFieldDto {
  final String name;
  final bool isProtected;

  const CustomFieldDto({required this.name, required this.isProtected});

  @override
  int get hashCode => name.hashCode ^ isProtected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomFieldDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          isProtected == other.isProtected;
}

class CustomFieldInputDto {
  final String name;
  final String value;
  final bool protected;

  const CustomFieldInputDto({
    required this.name,
    required this.value,
    required this.protected,
  });

  @override
  int get hashCode => name.hashCode ^ value.hashCode ^ protected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomFieldInputDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          value == other.value &&
          protected == other.protected;
}

class EntryDetail {
  final String uuid;
  final String title;
  final String username;
  final bool hasPassword;
  final String url;
  final String notes;
  final EntryKindDto kind;
  final List<String> tags;
  final List<CustomFieldDto> customFields;
  final List<AttachmentMeta> attachments;
  final PlatformInt64? creationTime;
  final PlatformInt64? lastModificationTime;
  final PlatformInt64? expiryTime;

  const EntryDetail({
    required this.uuid,
    required this.title,
    required this.username,
    required this.hasPassword,
    required this.url,
    required this.notes,
    required this.kind,
    required this.tags,
    required this.customFields,
    required this.attachments,
    this.creationTime,
    this.lastModificationTime,
    this.expiryTime,
  });

  @override
  int get hashCode =>
      uuid.hashCode ^
      title.hashCode ^
      username.hashCode ^
      hasPassword.hashCode ^
      url.hashCode ^
      notes.hashCode ^
      kind.hashCode ^
      tags.hashCode ^
      customFields.hashCode ^
      attachments.hashCode ^
      creationTime.hashCode ^
      lastModificationTime.hashCode ^
      expiryTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntryDetail &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          title == other.title &&
          username == other.username &&
          hasPassword == other.hasPassword &&
          url == other.url &&
          notes == other.notes &&
          kind == other.kind &&
          tags == other.tags &&
          customFields == other.customFields &&
          attachments == other.attachments &&
          creationTime == other.creationTime &&
          lastModificationTime == other.lastModificationTime &&
          expiryTime == other.expiryTime;
}

class EntryDraftDto {
  final EntryKindDto kind;
  final String title;
  final String? username;
  final String? password;
  final String? url;
  final String? notes;
  final List<String> tags;
  final List<CustomFieldInputDto> customFields;
  final String? totpUri;

  const EntryDraftDto({
    required this.kind,
    required this.title,
    this.username,
    this.password,
    this.url,
    this.notes,
    required this.tags,
    required this.customFields,
    this.totpUri,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      title.hashCode ^
      username.hashCode ^
      password.hashCode ^
      url.hashCode ^
      notes.hashCode ^
      tags.hashCode ^
      customFields.hashCode ^
      totpUri.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntryDraftDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          title == other.title &&
          username == other.username &&
          password == other.password &&
          url == other.url &&
          notes == other.notes &&
          tags == other.tags &&
          customFields == other.customFields &&
          totpUri == other.totpUri;
}

class EntryEditDto {
  final String? title;
  final String? username;
  final String? password;
  final String? url;
  final String? notes;
  final List<String>? tags;
  final List<CustomFieldInputDto>? customFields;
  final String? totpUri;

  const EntryEditDto({
    this.title,
    this.username,
    this.password,
    this.url,
    this.notes,
    this.tags,
    this.customFields,
    this.totpUri,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      username.hashCode ^
      password.hashCode ^
      url.hashCode ^
      notes.hashCode ^
      tags.hashCode ^
      customFields.hashCode ^
      totpUri.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntryEditDto &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          username == other.username &&
          password == other.password &&
          url == other.url &&
          notes == other.notes &&
          tags == other.tags &&
          customFields == other.customFields &&
          totpUri == other.totpUri;
}

enum EntryKindDto { credential, secureNote, totp }

class EntrySummary {
  final String uuid;
  final String title;
  final String username;
  final String url;
  final EntryKindDto kind;
  final bool hasTotp;
  final bool hasAttachments;
  final bool isExpired;
  final String groupUuid;
  final List<String> tags;

  const EntrySummary({
    required this.uuid,
    required this.title,
    required this.username,
    required this.url,
    required this.kind,
    required this.hasTotp,
    required this.hasAttachments,
    required this.isExpired,
    required this.groupUuid,
    required this.tags,
  });

  @override
  int get hashCode =>
      uuid.hashCode ^
      title.hashCode ^
      username.hashCode ^
      url.hashCode ^
      kind.hashCode ^
      hasTotp.hashCode ^
      hasAttachments.hashCode ^
      isExpired.hashCode ^
      groupUuid.hashCode ^
      tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntrySummary &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          title == other.title &&
          username == other.username &&
          url == other.url &&
          kind == other.kind &&
          hasTotp == other.hasTotp &&
          hasAttachments == other.hasAttachments &&
          isExpired == other.isExpired &&
          groupUuid == other.groupUuid &&
          tags == other.tags;
}

class GeneratedSecret {
  final String value;
  final double entropyBits;

  const GeneratedSecret({required this.value, required this.entropyBits});

  @override
  int get hashCode => value.hashCode ^ entropyBits.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GeneratedSecret &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          entropyBits == other.entropyBits;
}

enum GroupDeleteBehaviorDto { refuse, recurse }

class GroupNode {
  final String uuid;
  final String name;
  final List<GroupNode> children;
  final BigInt entryCount;

  const GroupNode({
    required this.uuid,
    required this.name,
    required this.children,
    required this.entryCount,
  });

  @override
  int get hashCode =>
      uuid.hashCode ^ name.hashCode ^ children.hashCode ^ entryCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupNode &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          name == other.name &&
          children == other.children &&
          entryCount == other.entryCount;
}

class HistorySummary {
  final String title;
  final String username;
  final PlatformInt64? lastModificationTime;

  const HistorySummary({
    required this.title,
    required this.username,
    this.lastModificationTime,
  });

  @override
  int get hashCode =>
      title.hashCode ^ username.hashCode ^ lastModificationTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistorySummary &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          username == other.username &&
          lastModificationTime == other.lastModificationTime;
}

@freezed
sealed class KeyfileRef with _$KeyfileRef {
  const KeyfileRef._();

  const factory KeyfileRef.path(String field0) = KeyfileRef_Path;
  const factory KeyfileRef.bytes(Uint8List field0) = KeyfileRef_Bytes;

  @override
  String toString() => 'KeyfileRef(***)';
}

enum LifecycleStateDto { resumed, inactive, hidden, paused, detached }

enum LockEvent { locked, unlocked }

enum MatchedFieldDto { title, username, url, notes, tags }

class PassphraseOptionsDto {
  final BigInt words;
  final String separator;

  const PassphraseOptionsDto({required this.words, required this.separator});

  @override
  int get hashCode => words.hashCode ^ separator.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PassphraseOptionsDto &&
          runtimeType == other.runtimeType &&
          words == other.words &&
          separator == other.separator;
}

class PasswordOptionsDto {
  final BigInt length;
  final bool lowercase;
  final bool uppercase;
  final bool digits;
  final bool symbols;
  final bool excludeAmbiguous;

  const PasswordOptionsDto({
    required this.length,
    required this.lowercase,
    required this.uppercase,
    required this.digits,
    required this.symbols,
    required this.excludeAmbiguous,
  });

  @override
  int get hashCode =>
      length.hashCode ^
      lowercase.hashCode ^
      uppercase.hashCode ^
      digits.hashCode ^
      symbols.hashCode ^
      excludeAmbiguous.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PasswordOptionsDto &&
          runtimeType == other.runtimeType &&
          length == other.length &&
          lowercase == other.lowercase &&
          uppercase == other.uppercase &&
          digits == other.digits &&
          symbols == other.symbols &&
          excludeAmbiguous == other.excludeAmbiguous;
}

@freezed
sealed class RevealField with _$RevealField {
  const RevealField._();

  const factory RevealField.password() = RevealField_Password;
  const factory RevealField.customField(String field0) =
      RevealField_CustomField;
  const factory RevealField.totpUri() = RevealField_TotpUri;
}

class S3ConfigDto {
  final String bucket;
  final String key;
  final String region;
  final String? endpoint;
  final bool pathStyle;
  final String accessKeyId;
  final String secretAccessKey;

  const S3ConfigDto({
    required this.bucket,
    required this.key,
    required this.region,
    this.endpoint,
    required this.pathStyle,
    required this.accessKeyId,
    required this.secretAccessKey,
  });

  @override
  int get hashCode =>
      bucket.hashCode ^
      key.hashCode ^
      region.hashCode ^
      endpoint.hashCode ^
      pathStyle.hashCode ^
      accessKeyId.hashCode ^
      secretAccessKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is S3ConfigDto &&
          runtimeType == other.runtimeType &&
          bucket == other.bucket &&
          key == other.key &&
          region == other.region &&
          endpoint == other.endpoint &&
          pathStyle == other.pathStyle &&
          accessKeyId == other.accessKeyId &&
          secretAccessKey == other.secretAccessKey;
}

class SearchFieldMatchDto {
  final MatchedFieldDto field;
  final List<(int, int)> ranges;

  const SearchFieldMatchDto({required this.field, required this.ranges});

  @override
  int get hashCode => field.hashCode ^ ranges.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchFieldMatchDto &&
          runtimeType == other.runtimeType &&
          field == other.field &&
          ranges == other.ranges;
}

class SearchHit {
  final EntrySummary entry;
  final List<SearchFieldMatchDto> matches;

  const SearchHit({required this.entry, required this.matches});

  @override
  int get hashCode => entry.hashCode ^ matches.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchHit &&
          runtimeType == other.runtimeType &&
          entry == other.entry &&
          matches == other.matches;
}

enum SearchModeDto { substring, wildcard, fuzzy }

class SearchOptionsDto {
  final String query;
  final SearchModeDto mode;
  final SearchScopeDto scope;
  final bool includeRecycled;

  const SearchOptionsDto({
    required this.query,
    required this.mode,
    required this.scope,
    required this.includeRecycled,
  });

  @override
  int get hashCode =>
      query.hashCode ^
      mode.hashCode ^
      scope.hashCode ^
      includeRecycled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchOptionsDto &&
          runtimeType == other.runtimeType &&
          query == other.query &&
          mode == other.mode &&
          scope == other.scope &&
          includeRecycled == other.includeRecycled;
}

@freezed
sealed class SearchScopeDto with _$SearchScopeDto {
  const SearchScopeDto._();

  const factory SearchScopeDto.all() = SearchScopeDto_All;
  const factory SearchScopeDto.groupSubtree(String field0) =
      SearchScopeDto_GroupSubtree;
  const factory SearchScopeDto.tag(String field0) = SearchScopeDto_Tag;
}

@freezed
sealed class SyncEvent with _$SyncEvent {
  const SyncEvent._();

  const factory SyncEvent.started() = SyncEvent_Started;
  const factory SyncEvent.activity() = SyncEvent_Activity;
  const factory SyncEvent.done(SyncOutcomeDto field0) = SyncEvent_Done;
  const factory SyncEvent.failed(HidlinsApiError field0) = SyncEvent_Failed;
}

@freezed
sealed class SyncOutcomeDto with _$SyncOutcomeDto {
  const SyncOutcomeDto._();

  const factory SyncOutcomeDto.alreadyInSync() = SyncOutcomeDto_AlreadyInSync;
  const factory SyncOutcomeDto.pushed({required bool isFirstSeed}) =
      SyncOutcomeDto_Pushed;
  const factory SyncOutcomeDto.fastReplaced() = SyncOutcomeDto_FastReplaced;
  const factory SyncOutcomeDto.merged({
    required BigInt entriesAdded,
    required BigInt entriesModified,
    required BigInt entriesRemoved,
  }) = SyncOutcomeDto_Merged;
  const factory SyncOutcomeDto.unknown() = SyncOutcomeDto_Unknown;
}

class SyncStatusDto {
  final bool configured;
  final bool inFlight;
  final SyncOutcomeDto? lastOutcome;

  const SyncStatusDto({
    required this.configured,
    required this.inFlight,
    this.lastOutcome,
  });

  @override
  int get hashCode =>
      configured.hashCode ^ inFlight.hashCode ^ lastOutcome.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncStatusDto &&
          runtimeType == other.runtimeType &&
          configured == other.configured &&
          inFlight == other.inFlight &&
          lastOutcome == other.lastOutcome;
}

class TotpCode {
  final String code;
  final BigInt remainingSecs;
  final BigInt period;

  const TotpCode({
    required this.code,
    required this.remainingSecs,
    required this.period,
  });

  @override
  int get hashCode => code.hashCode ^ remainingSecs.hashCode ^ period.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TotpCode &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          remainingSecs == other.remainingSecs &&
          period == other.period;
}

class UiPrefs {
  final String? themeMode;
  final int? windowX;
  final int? windowY;
  final int? windowWidth;
  final int? windowHeight;
  final String? lastVault;
  final double? listPaneWidth;

  const UiPrefs({
    this.themeMode,
    this.windowX,
    this.windowY,
    this.windowWidth,
    this.windowHeight,
    this.lastVault,
    this.listPaneWidth,
  });

  @override
  int get hashCode =>
      themeMode.hashCode ^
      windowX.hashCode ^
      windowY.hashCode ^
      windowWidth.hashCode ^
      windowHeight.hashCode ^
      lastVault.hashCode ^
      listPaneWidth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiPrefs &&
          runtimeType == other.runtimeType &&
          themeMode == other.themeMode &&
          windowX == other.windowX &&
          windowY == other.windowY &&
          windowWidth == other.windowWidth &&
          windowHeight == other.windowHeight &&
          lastVault == other.lastVault &&
          listPaneWidth == other.listPaneWidth;
}

class VaultSummary {
  final String name;
  final String path;
  final bool hasKeyfile;
  final bool hasSync;

  const VaultSummary({
    required this.name,
    required this.path,
    required this.hasKeyfile,
    required this.hasSync,
  });

  @override
  int get hashCode =>
      name.hashCode ^ path.hashCode ^ hasKeyfile.hashCode ^ hasSync.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultSummary &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          hasKeyfile == other.hasKeyfile &&
          hasSync == other.hasSync;
}

class VaultTree {
  final GroupNode root;
  final List<EntrySummary> entries;

  const VaultTree({required this.root, required this.entries});

  @override
  int get hashCode => root.hashCode ^ entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultTree &&
          runtimeType == other.runtimeType &&
          root == other.root &&
          entries == other.entries;
}
