// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// GENERATED by flutter_rust_bridge — DO NOT EDIT

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

@freezed
sealed class HidlinsApiError with _$HidlinsApiError implements FrbException {
  const HidlinsApiError._();

  const factory HidlinsApiError.authenticationFailed() =
      HidlinsApiError_AuthenticationFailed;
  const factory HidlinsApiError.vaultLocked() = HidlinsApiError_VaultLocked;
  const factory HidlinsApiError.vaultBusySyncing() =
      HidlinsApiError_VaultBusySyncing;
  const factory HidlinsApiError.vaultContended({int? holderPid}) =
      HidlinsApiError_VaultContended;
  const factory HidlinsApiError.pathExists({required String path}) =
      HidlinsApiError_PathExists;
  const factory HidlinsApiError.fileNotFound({required String path}) =
      HidlinsApiError_FileNotFound;
  const factory HidlinsApiError.keyfileRequired() =
      HidlinsApiError_KeyfileRequired;
  const factory HidlinsApiError.registryChanged() =
      HidlinsApiError_RegistryChanged;
  const factory HidlinsApiError.invalidFormat() = HidlinsApiError_InvalidFormat;
  const factory HidlinsApiError.registryMalformed() =
      HidlinsApiError_RegistryMalformed;
  const factory HidlinsApiError.syncNotConfigured() =
      HidlinsApiError_SyncNotConfigured;
  const factory HidlinsApiError.syncRemoteUnreachable({String? endpoint}) =
      HidlinsApiError_SyncRemoteUnreachable;
  const factory HidlinsApiError.syncAuthFailed() =
      HidlinsApiError_SyncAuthFailed;
  const factory HidlinsApiError.syncConflictUnresolvable({
    required String backupPath,
  }) = HidlinsApiError_SyncConflictUnresolvable;
  const factory HidlinsApiError.syncDuplicateTarget({
    required String existingVault,
  }) = HidlinsApiError_SyncDuplicateTarget;
  const factory HidlinsApiError.invalidInput({
    required String field,
    required String reason,
  }) = HidlinsApiError_InvalidInput;
  const factory HidlinsApiError.io({required String context}) =
      HidlinsApiError_Io;
  const factory HidlinsApiError.internal({required String context}) =
      HidlinsApiError_Internal;
}
