// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// GENERATED by flutter_rust_bridge — DO NOT EDIT

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/session.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'dto.dart';
import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AppSessionPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSessionPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  AppSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSession(
    dynamic raw,
  );

  @protected
  AppSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSession(
    dynamic raw,
  );

  @protected
  AppSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSession(
    dynamic raw,
  );

  @protected
  RustStreamSink<ClipboardEvent> dco_decode_StreamSink_clipboard_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<LockEvent> dco_decode_StreamSink_lock_event_Sse(dynamic raw);

  @protected
  RustStreamSink<SyncEvent> dco_decode_StreamSink_sync_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppInitConfig dco_decode_app_init_config(dynamic raw);

  @protected
  AttachmentMeta dco_decode_attachment_meta(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AppInitConfig dco_decode_box_autoadd_app_init_config(dynamic raw);

  @protected
  CopyField dco_decode_box_autoadd_copy_field(dynamic raw);

  @protected
  EntryDraftDto dco_decode_box_autoadd_entry_draft_dto(dynamic raw);

  @protected
  EntryEditDto dco_decode_box_autoadd_entry_edit_dto(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  HidlinsApiError dco_decode_box_autoadd_hidlins_api_error(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  KeyfileRef dco_decode_box_autoadd_keyfile_ref(dynamic raw);

  @protected
  PassphraseOptionsDto dco_decode_box_autoadd_passphrase_options_dto(
    dynamic raw,
  );

  @protected
  PasswordOptionsDto dco_decode_box_autoadd_password_options_dto(dynamic raw);

  @protected
  RevealField dco_decode_box_autoadd_reveal_field(dynamic raw);

  @protected
  S3ConfigDto dco_decode_box_autoadd_s_3_config_dto(dynamic raw);

  @protected
  SearchOptionsDto dco_decode_box_autoadd_search_options_dto(dynamic raw);

  @protected
  SyncOutcomeDto dco_decode_box_autoadd_sync_outcome_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  UiPrefs dco_decode_box_autoadd_ui_prefs(dynamic raw);

  @protected
  ClipboardEvent dco_decode_clipboard_event(dynamic raw);

  @protected
  CopyField dco_decode_copy_field(dynamic raw);

  @protected
  CustomFieldDto dco_decode_custom_field_dto(dynamic raw);

  @protected
  CustomFieldInputDto dco_decode_custom_field_input_dto(dynamic raw);

  @protected
  EntryDetail dco_decode_entry_detail(dynamic raw);

  @protected
  EntryDraftDto dco_decode_entry_draft_dto(dynamic raw);

  @protected
  EntryEditDto dco_decode_entry_edit_dto(dynamic raw);

  @protected
  EntryKindDto dco_decode_entry_kind_dto(dynamic raw);

  @protected
  EntrySummary dco_decode_entry_summary(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  GeneratedSecret dco_decode_generated_secret(dynamic raw);

  @protected
  GroupDeleteBehaviorDto dco_decode_group_delete_behavior_dto(dynamic raw);

  @protected
  GroupNode dco_decode_group_node(dynamic raw);

  @protected
  HidlinsApiError dco_decode_hidlins_api_error(dynamic raw);

  @protected
  HistorySummary dco_decode_history_summary(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  KeyfileRef dco_decode_keyfile_ref(dynamic raw);

  @protected
  LifecycleStateDto dco_decode_lifecycle_state_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AttachmentMeta> dco_decode_list_attachment_meta(dynamic raw);

  @protected
  List<CustomFieldDto> dco_decode_list_custom_field_dto(dynamic raw);

  @protected
  List<CustomFieldInputDto> dco_decode_list_custom_field_input_dto(dynamic raw);

  @protected
  List<EntrySummary> dco_decode_list_entry_summary(dynamic raw);

  @protected
  List<GroupNode> dco_decode_list_group_node(dynamic raw);

  @protected
  List<HistorySummary> dco_decode_list_history_summary(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(int, int)> dco_decode_list_record_u_32_u_32(dynamic raw);

  @protected
  List<SearchFieldMatchDto> dco_decode_list_search_field_match_dto(dynamic raw);

  @protected
  List<SearchHit> dco_decode_list_search_hit(dynamic raw);

  @protected
  List<VaultSummary> dco_decode_list_vault_summary(dynamic raw);

  @protected
  LockEvent dco_decode_lock_event(dynamic raw);

  @protected
  MatchedFieldDto dco_decode_matched_field_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  KeyfileRef? dco_decode_opt_box_autoadd_keyfile_ref(dynamic raw);

  @protected
  SyncOutcomeDto? dco_decode_opt_box_autoadd_sync_outcome_dto(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  List<CustomFieldInputDto>? dco_decode_opt_list_custom_field_input_dto(
    dynamic raw,
  );

  @protected
  PassphraseOptionsDto dco_decode_passphrase_options_dto(dynamic raw);

  @protected
  PasswordOptionsDto dco_decode_password_options_dto(dynamic raw);

  @protected
  (int, int) dco_decode_record_u_32_u_32(dynamic raw);

  @protected
  RevealField dco_decode_reveal_field(dynamic raw);

  @protected
  S3ConfigDto dco_decode_s_3_config_dto(dynamic raw);

  @protected
  SearchFieldMatchDto dco_decode_search_field_match_dto(dynamic raw);

  @protected
  SearchHit dco_decode_search_hit(dynamic raw);

  @protected
  SearchModeDto dco_decode_search_mode_dto(dynamic raw);

  @protected
  SearchOptionsDto dco_decode_search_options_dto(dynamic raw);

  @protected
  SearchScopeDto dco_decode_search_scope_dto(dynamic raw);

  @protected
  SyncEvent dco_decode_sync_event(dynamic raw);

  @protected
  SyncOutcomeDto dco_decode_sync_outcome_dto(dynamic raw);

  @protected
  SyncStatusDto dco_decode_sync_status_dto(dynamic raw);

  @protected
  TotpCode dco_decode_totp_code(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  UiPrefs dco_decode_ui_prefs(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VaultSummary dco_decode_vault_summary(dynamic raw);

  @protected
  VaultTree dco_decode_vault_tree(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  AppSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSession(
    SseDeserializer deserializer,
  );

  @protected
  AppSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSession(
    SseDeserializer deserializer,
  );

  @protected
  AppSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSession(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ClipboardEvent> sse_decode_StreamSink_clipboard_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<LockEvent> sse_decode_StreamSink_lock_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SyncEvent> sse_decode_StreamSink_sync_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppInitConfig sse_decode_app_init_config(SseDeserializer deserializer);

  @protected
  AttachmentMeta sse_decode_attachment_meta(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AppInitConfig sse_decode_box_autoadd_app_init_config(
    SseDeserializer deserializer,
  );

  @protected
  CopyField sse_decode_box_autoadd_copy_field(SseDeserializer deserializer);

  @protected
  EntryDraftDto sse_decode_box_autoadd_entry_draft_dto(
    SseDeserializer deserializer,
  );

  @protected
  EntryEditDto sse_decode_box_autoadd_entry_edit_dto(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  HidlinsApiError sse_decode_box_autoadd_hidlins_api_error(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  KeyfileRef sse_decode_box_autoadd_keyfile_ref(SseDeserializer deserializer);

  @protected
  PassphraseOptionsDto sse_decode_box_autoadd_passphrase_options_dto(
    SseDeserializer deserializer,
  );

  @protected
  PasswordOptionsDto sse_decode_box_autoadd_password_options_dto(
    SseDeserializer deserializer,
  );

  @protected
  RevealField sse_decode_box_autoadd_reveal_field(SseDeserializer deserializer);

  @protected
  S3ConfigDto sse_decode_box_autoadd_s_3_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  SearchOptionsDto sse_decode_box_autoadd_search_options_dto(
    SseDeserializer deserializer,
  );

  @protected
  SyncOutcomeDto sse_decode_box_autoadd_sync_outcome_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  UiPrefs sse_decode_box_autoadd_ui_prefs(SseDeserializer deserializer);

  @protected
  ClipboardEvent sse_decode_clipboard_event(SseDeserializer deserializer);

  @protected
  CopyField sse_decode_copy_field(SseDeserializer deserializer);

  @protected
  CustomFieldDto sse_decode_custom_field_dto(SseDeserializer deserializer);

  @protected
  CustomFieldInputDto sse_decode_custom_field_input_dto(
    SseDeserializer deserializer,
  );

  @protected
  EntryDetail sse_decode_entry_detail(SseDeserializer deserializer);

  @protected
  EntryDraftDto sse_decode_entry_draft_dto(SseDeserializer deserializer);

  @protected
  EntryEditDto sse_decode_entry_edit_dto(SseDeserializer deserializer);

  @protected
  EntryKindDto sse_decode_entry_kind_dto(SseDeserializer deserializer);

  @protected
  EntrySummary sse_decode_entry_summary(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  GeneratedSecret sse_decode_generated_secret(SseDeserializer deserializer);

  @protected
  GroupDeleteBehaviorDto sse_decode_group_delete_behavior_dto(
    SseDeserializer deserializer,
  );

  @protected
  GroupNode sse_decode_group_node(SseDeserializer deserializer);

  @protected
  HidlinsApiError sse_decode_hidlins_api_error(SseDeserializer deserializer);

  @protected
  HistorySummary sse_decode_history_summary(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  KeyfileRef sse_decode_keyfile_ref(SseDeserializer deserializer);

  @protected
  LifecycleStateDto sse_decode_lifecycle_state_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AttachmentMeta> sse_decode_list_attachment_meta(
    SseDeserializer deserializer,
  );

  @protected
  List<CustomFieldDto> sse_decode_list_custom_field_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<CustomFieldInputDto> sse_decode_list_custom_field_input_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<EntrySummary> sse_decode_list_entry_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<GroupNode> sse_decode_list_group_node(SseDeserializer deserializer);

  @protected
  List<HistorySummary> sse_decode_list_history_summary(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(int, int)> sse_decode_list_record_u_32_u_32(
    SseDeserializer deserializer,
  );

  @protected
  List<SearchFieldMatchDto> sse_decode_list_search_field_match_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<SearchHit> sse_decode_list_search_hit(SseDeserializer deserializer);

  @protected
  List<VaultSummary> sse_decode_list_vault_summary(
    SseDeserializer deserializer,
  );

  @protected
  LockEvent sse_decode_lock_event(SseDeserializer deserializer);

  @protected
  MatchedFieldDto sse_decode_matched_field_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  KeyfileRef? sse_decode_opt_box_autoadd_keyfile_ref(
    SseDeserializer deserializer,
  );

  @protected
  SyncOutcomeDto? sse_decode_opt_box_autoadd_sync_outcome_dto(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  List<CustomFieldInputDto>? sse_decode_opt_list_custom_field_input_dto(
    SseDeserializer deserializer,
  );

  @protected
  PassphraseOptionsDto sse_decode_passphrase_options_dto(
    SseDeserializer deserializer,
  );

  @protected
  PasswordOptionsDto sse_decode_password_options_dto(
    SseDeserializer deserializer,
  );

  @protected
  (int, int) sse_decode_record_u_32_u_32(SseDeserializer deserializer);

  @protected
  RevealField sse_decode_reveal_field(SseDeserializer deserializer);

  @protected
  S3ConfigDto sse_decode_s_3_config_dto(SseDeserializer deserializer);

  @protected
  SearchFieldMatchDto sse_decode_search_field_match_dto(
    SseDeserializer deserializer,
  );

  @protected
  SearchHit sse_decode_search_hit(SseDeserializer deserializer);

  @protected
  SearchModeDto sse_decode_search_mode_dto(SseDeserializer deserializer);

  @protected
  SearchOptionsDto sse_decode_search_options_dto(SseDeserializer deserializer);

  @protected
  SearchScopeDto sse_decode_search_scope_dto(SseDeserializer deserializer);

  @protected
  SyncEvent sse_decode_sync_event(SseDeserializer deserializer);

  @protected
  SyncOutcomeDto sse_decode_sync_outcome_dto(SseDeserializer deserializer);

  @protected
  SyncStatusDto sse_decode_sync_status_dto(SseDeserializer deserializer);

  @protected
  TotpCode sse_decode_totp_code(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  UiPrefs sse_decode_ui_prefs(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VaultSummary sse_decode_vault_summary(SseDeserializer deserializer);

  @protected
  VaultTree sse_decode_vault_tree(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSession(
    AppSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSession(
    AppSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSession(
    AppSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_clipboard_event_Sse(
    RustStreamSink<ClipboardEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_lock_event_Sse(
    RustStreamSink<LockEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_sync_event_Sse(
    RustStreamSink<SyncEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_app_init_config(AppInitConfig self, SseSerializer serializer);

  @protected
  void sse_encode_attachment_meta(
    AttachmentMeta self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_app_init_config(
    AppInitConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_copy_field(
    CopyField self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_entry_draft_dto(
    EntryDraftDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_entry_edit_dto(
    EntryEditDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_hidlins_api_error(
    HidlinsApiError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_keyfile_ref(
    KeyfileRef self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_passphrase_options_dto(
    PassphraseOptionsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_password_options_dto(
    PasswordOptionsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_reveal_field(
    RevealField self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_s_3_config_dto(
    S3ConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_search_options_dto(
    SearchOptionsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sync_outcome_dto(
    SyncOutcomeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ui_prefs(UiPrefs self, SseSerializer serializer);

  @protected
  void sse_encode_clipboard_event(
    ClipboardEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_copy_field(CopyField self, SseSerializer serializer);

  @protected
  void sse_encode_custom_field_dto(
    CustomFieldDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_custom_field_input_dto(
    CustomFieldInputDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_entry_detail(EntryDetail self, SseSerializer serializer);

  @protected
  void sse_encode_entry_draft_dto(EntryDraftDto self, SseSerializer serializer);

  @protected
  void sse_encode_entry_edit_dto(EntryEditDto self, SseSerializer serializer);

  @protected
  void sse_encode_entry_kind_dto(EntryKindDto self, SseSerializer serializer);

  @protected
  void sse_encode_entry_summary(EntrySummary self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_generated_secret(
    GeneratedSecret self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_delete_behavior_dto(
    GroupDeleteBehaviorDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_node(GroupNode self, SseSerializer serializer);

  @protected
  void sse_encode_hidlins_api_error(
    HidlinsApiError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_history_summary(
    HistorySummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_keyfile_ref(KeyfileRef self, SseSerializer serializer);

  @protected
  void sse_encode_lifecycle_state_dto(
    LifecycleStateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_attachment_meta(
    List<AttachmentMeta> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_custom_field_dto(
    List<CustomFieldDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_custom_field_input_dto(
    List<CustomFieldInputDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_entry_summary(
    List<EntrySummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_node(
    List<GroupNode> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_history_summary(
    List<HistorySummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_u_32_u_32(
    List<(int, int)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_search_field_match_dto(
    List<SearchFieldMatchDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_search_hit(
    List<SearchHit> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_vault_summary(
    List<VaultSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_lock_event(LockEvent self, SseSerializer serializer);

  @protected
  void sse_encode_matched_field_dto(
    MatchedFieldDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_keyfile_ref(
    KeyfileRef? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_sync_outcome_dto(
    SyncOutcomeDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_custom_field_input_dto(
    List<CustomFieldInputDto>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_passphrase_options_dto(
    PassphraseOptionsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_password_options_dto(
    PasswordOptionsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_32_u_32((int, int) self, SseSerializer serializer);

  @protected
  void sse_encode_reveal_field(RevealField self, SseSerializer serializer);

  @protected
  void sse_encode_s_3_config_dto(S3ConfigDto self, SseSerializer serializer);

  @protected
  void sse_encode_search_field_match_dto(
    SearchFieldMatchDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_search_hit(SearchHit self, SseSerializer serializer);

  @protected
  void sse_encode_search_mode_dto(SearchModeDto self, SseSerializer serializer);

  @protected
  void sse_encode_search_options_dto(
    SearchOptionsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_search_scope_dto(
    SearchScopeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_event(SyncEvent self, SseSerializer serializer);

  @protected
  void sse_encode_sync_outcome_dto(
    SyncOutcomeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_status_dto(SyncStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_totp_code(TotpCode self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_ui_prefs(UiPrefs self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_vault_summary(VaultSummary self, SseSerializer serializer);

  @protected
  void sse_encode_vault_tree(VaultTree self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSession(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSession(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSessionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_app_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSession',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSession =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSessionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSession(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSession(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSessionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_app_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSession',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSession =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSessionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
