// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// GENERATED by flutter_rust_bridge — DO NOT EDIT

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../dto.dart';
import '../error.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `attach_platform_lock_sources`, `clear_totp_cache_inner`, `clear_totp_cache`, `do_lock`, `install_lock_sink`, `invalidate_totp`, `is_unlocked`, `kill`, `lifecycle_from_u8`, `lifecycle_to_u8`, `lock_state`, `new`, `push_lock_event`, `push_sync_event`, `require_vault_mut`, `require_vault`, `secret_uri`, `spawn_ticker`, `stop_server_runtime`, `tick_inner`, `unlock_inner`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ClearUnlockingOnDrop`, `SessionCredentials`, `SessionServerRuntime`, `SessionState`, `TickerProgress`, `TotpSnapshot`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`, `drop`, `drop`, `drop`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

Future<String> apiVersion() => RustLib.instance.api.crateApiSessionApiVersion();

Future<AppSession> initApp({required AppInitConfig cfg}) =>
    RustLib.instance.api.crateApiSessionInitApp(cfg: cfg);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AppSession>>
abstract class AppSession implements RustOpaqueInterface {
  Future<void> addAttachment({
    required String uuid,
    required String sourcePath,
  });

  /// Begin pair-and-import without creating a local vault or registration.
  Future<PairingPromptDto> beginPairImport({
    required String name,
    required String masterPassword,
    KeyfileRef? keyfile,
    required List<LocalEndpointDto> candidates,
  });

  /// Begin XX pairing for the currently unlocked client vault.
  Future<PairingPromptDto> beginPairing();

  /// Cancel foreground client transfer/pairing work without changing trust.
  Future<void> cancelSync();

  /// Change the vault password and rewrap (never replace) its local Noise identity.
  Future<void> changeMasterPassword({
    required String current,
    required String newPassword,
  });

  Future<void> clearExpiration({required String uuid});

  Future<void> clearSyncConfig({required String name});

  Future<void> closePairingWindow();

  Future<void> configureLocalSync({required LocalSyncRoleDto role});

  /// Confirm either a local client prompt or an inbound server prompt.
  /// Key material and transcript hashes never cross this boundary.
  Future<VaultSummary?> confirmPairing({
    required String transactionHandle,
    required bool accepted,
    required String peerDisplayName,
  });

  Future<void> copyEntryField({required String uuid, required CopyField field});

  Future<String> createEntry({
    required String group,
    required EntryDraftDto draft,
  });

  Future<String> createGroup({required String parent, required String name});

  Future<VaultSummary> createVault({
    required String name,
    required String masterPassword,
    String? fileName,
    KeyfileRef? keyfile,
    required bool confirmedNoRecovery,
  });

  Future<void> deleteEntry({required String uuid});

  Future<void> deleteGroup({
    required String uuid,
    required GroupDeleteBehaviorDto behavior,
  });

  Future<void> deregisterVault({
    required String name,
    required bool deleteFile,
  });

  /// Number of lock events frb refused to deliver to Dart, monotonic for
  /// the session's lifetime (it never resets, including on resubscribe).
  ///
  /// An increase since the caller last read it means the UI may be
  /// rendering stale lock state; see [`crate::event::StreamSinkAdapter`].
  /// Exposed because the project has no logging facility and a dropped
  /// `Locked` is otherwise unobservable.
  BigInt droppedLockEvents();

  Future<EntryDetail> entryDetail({required String uuid});

  Future<List<HistorySummary>> entryHistory({required String uuid});

  Future<GeneratedSecret> generatePassphrase({
    required PassphraseOptionsDto opts,
  });

  Future<GeneratedSecret> generatePassword({required PasswordOptionsDto opts});

  /// Load UI preferences from the state directory.
  ///
  /// Returns defaults when the file is missing or corrupt — prefs are
  /// never a blocking failure.
  Future<UiPrefs> getPrefs();

  Future<List<AttachmentMeta>> listAttachments({required String uuid});

  Future<List<SyncPeerDto>> listSyncPeers();

  Future<List<String>> listTags();

  Future<List<VaultSummary>> listVaults();

  Future<DiscoveryStatusDto> localDiscoveryStatus();

  /// Return policy-approved local bind candidates for a desktop server.
  /// Mobile targets reject this before interface enumeration.
  Future<List<LocalEndpointDto>> localServerEndpoints();

  Future<SyncStatusDto> localSyncStatus();

  /// Subscribe to lock-state events.
  ///
  /// Registration atomically pushes an authoritative snapshot of the
  /// current state (`Locked`/`Unlocked`) as the first event, so a
  /// subscriber never has to guess the state it started from and a
  /// transition racing the subscription cannot be observed as silence. On
  /// a dead (shut-down) session the snapshot is `Locked` and the stream is
  /// closed immediately; [`Self::shutdown`] also closes an active stream.
  /// Client protocol: end-of-stream, or an *increase* in the monotonic
  /// [`Self::dropped_lock_events`] counter since the client last read it,
  /// means cached lock state is stale — treat the vault as locked and
  /// resubscribe for a fresh snapshot (which resets nothing; compare
  /// against the newly read counter value from then on).
  Stream<LockEvent> lockEvents();

  Future<void> lockNow();

  Future<void> moveEntry({required String uuid, required String group});

  Future<void> moveGroup({required String uuid, required String parent});

  Future<void> openPairingWindow();

  /// Poll the platform discovery adapter and apply only Rust-validated routes.
  Future<DiscoveryStatusDto> pollLocalDiscovery();

  /// Prepare a non-secret, single-use native clipboard handoff.
  ///
  /// Desktop uses the Rust clipboard directly and therefore returns a typed
  /// unsupported result. Mobile Dart receives only this ticket; the
  /// protected value remains zeroizing Rust state until a native adapter
  /// consumes it or the session locks.
  Future<ClipboardTransferTicket> prepareClipboardTransfer({
    required String uuid,
    required CopyField field,
  });

  Future<void> purgeEntry({required String uuid});

  Future<VaultSummary> registerExistingVault({
    required String name,
    required String kdbxPath,
    KeyfileRef? keyfile,
  });

  Future<void> removeAttachment({required String uuid, required String key});

  Future<void> renameGroup({required String uuid, required String name});

  Future<void> renameSyncPeer({
    required String peerId,
    required String displayName,
  });

  void reportActivity();

  LockEvent reportLifecycleState({required LifecycleStateDto state});

  Future<String> revealField({
    required String uuid,
    required RevealField field,
  });

  Future<void> revokeSyncPeer({required String peerId});

  Future<void> saveAttachmentTo({
    required String uuid,
    required String key,
    required String destPath,
  });

  Future<List<SearchHit>> search({required SearchOptionsDto opts});

  Future<void> setDiscoveryCandidates({
    required DiscoveryPermissionDto permission,
    required List<LocalEndpointDto> candidates,
  });

  Future<void> setExpiration({
    required String uuid,
    required PlatformInt64 epochSecs,
  });

  /// Persist UI preferences to the state directory.
  Future<void> setPrefs({required UiPrefs prefs});

  Future<void> shutdown();

  /// Consume the once-per-process startup attempt after the application has
  /// completed its platform discovery pass.
  ///
  /// The work remains nonblocking and best effort: the already-open local
  /// vault stays available, and any network failure is reported through the
  /// sync event stream.
  Future<void> startStartupSync();

  Future<LocalEndpointDto> startSyncServer({
    required LocalEndpointDto endpoint,
  });

  Future<List<String>> startupWarnings();

  Future<void> stopSyncServer();

  Stream<SyncEvent> syncEvents();

  Future<SyncOutcomeDto> syncNow();

  Future<SyncStatusDto> syncStatus();

  /// Compute the current TOTP code for a cached entry.
  ///
  /// This method reads the TOTP cache via a `RwLock` read guard and
  /// NEVER takes the session mutex (threading rule 3). The cache is
  /// populated by [`Self::entry_detail`] when the entry kind is TOTP.
  ///
  /// Returns `Err(Internal)` on cache miss — callers must open the
  /// entry detail before requesting TOTP codes.
  TotpCode totpNow({required String uuid});

  Future<VaultTree> unlock({
    required String name,
    required String masterPassword,
    KeyfileRef? keyfile,
  });

  Future<void> updateEntry({required String uuid, required EntryEditDto edit});

  Future<VaultTree> vaultTree();
}
