// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// GENERATED by flutter_rust_bridge — DO NOT EDIT

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../dto.dart';
import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clear_totp_cache_inner`, `clear_totp_cache`, `do_lock`, `install_lock_sink`, `invalidate_totp`, `is_unlocked`, `kill`, `lifecycle_from_u8`, `lifecycle_to_u8`, `lock_state`, `maybe_sync_after_save`, `new`, `push_lock_event`, `push_sync_event`, `require_vault_mut`, `require_vault`, `secret_uri`, `spawn_ticker`, `tick_inner`, `unlock_inner`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ClearUnlockingOnDrop`, `SessionCredentials`, `SessionState`, `TotpSnapshot`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`, `drop`, `drop`, `drop`, `fmt`, `fmt`

Future<String> apiVersion() => RustLib.instance.api.crateApiSessionApiVersion();

Future<AppSession> initApp({required AppInitConfig cfg}) =>
    RustLib.instance.api.crateApiSessionInitApp(cfg: cfg);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AppSession>>
abstract class AppSession implements RustOpaqueInterface {
  Future<void> addAttachment({
    required String uuid,
    required String sourcePath,
  });

  /// Bootstrap a vault from a remote S3 target (design A3).
  ///
  /// State machine:
  /// 1. Guards (duplicate target, name/path exists)
  /// 2. Build transport from config, fetch remote object
  /// 3. Validate password/keyfile via `Vault::open_from_bytes` —
  ///    wrong password fails BEFORE any install
  /// 4. `write_atomic` install into the state dir
  /// 5. Register vault + persist pre-sealed sync config
  /// 6. One standard `sync_now` establishes synced-base pointers
  /// 7. Rollback on any failure after step 4
  Future<VaultSummary> bootstrapVaultFromRemote({
    required String name,
    required S3ConfigDto cfg,
    required String masterPassword,
    KeyfileRef? keyfile,
  });

  /// Change the master password (design A5, FR-004).
  ///
  /// Sequence: verify current → change vault password → REPLACE
  /// `SessionCredentials` immediately (before the registry write) →
  /// if RST-CRED-1 sync credentials exist, decrypt with old master,
  /// re-encrypt with new master, persist → registry save → vault save.
  ///
  /// On registry-write failure the vault change AND the credential
  /// replacement both stand; the error instructs re-entering S3
  /// credentials (no silent auth breakage).
  ///
  /// # Panics
  ///
  /// Panics if the vault is present but not registered (impossible via
  /// the session API).
  Future<void> changeMasterPassword({
    required String current,
    required String newPassword,
  });

  Future<void> clearExpiration({required String uuid});

  Future<void> clearSyncConfig({required String name});

  Stream<ClipboardEvent> clipboardEvents();

  Future<void> configureSync({required S3ConfigDto cfg});

  Future<void> copyEntryField({required String uuid, required CopyField field});

  Future<String> createEntry({
    required String group,
    required EntryDraftDto draft,
  });

  Future<String> createGroup({required String parent, required String name});

  Future<VaultSummary> createVault({
    required String name,
    required String masterPassword,
    String? fileName,
    KeyfileRef? keyfile,
    required bool confirmedNoRecovery,
  });

  Future<void> deleteEntry({required String uuid});

  Future<void> deleteGroup({
    required String uuid,
    required GroupDeleteBehaviorDto behavior,
  });

  Future<void> deregisterVault({
    required String name,
    required bool deleteFile,
  });

  /// Number of lock events frb refused to deliver to Dart, monotonic for
  /// the session's lifetime (it never resets, including on resubscribe).
  ///
  /// An increase since the caller last read it means the UI may be
  /// rendering stale lock state; see [`crate::event::StreamSinkAdapter`].
  /// Exposed because the project has no logging facility and a dropped
  /// `Locked` is otherwise unobservable.
  BigInt droppedLockEvents();

  Future<EntryDetail> entryDetail({required String uuid});

  Future<List<HistorySummary>> entryHistory({required String uuid});

  Future<GeneratedSecret> generatePassphrase({
    required PassphraseOptionsDto opts,
  });

  Future<GeneratedSecret> generatePassword({required PasswordOptionsDto opts});

  /// Load UI preferences from the state directory.
  ///
  /// Returns defaults when the file is missing or corrupt — prefs are
  /// never a blocking failure.
  Future<UiPrefs> getPrefs();

  Future<List<AttachmentMeta>> listAttachments({required String uuid});

  Future<List<String>> listTags();

  Future<List<VaultSummary>> listVaults();

  /// Subscribe to lock-state events.
  ///
  /// Registration atomically pushes an authoritative snapshot of the
  /// current state (`Locked`/`Unlocked`) as the first event, so a
  /// subscriber never has to guess the state it started from and a
  /// transition racing the subscription cannot be observed as silence. On
  /// a dead (shut-down) session the snapshot is `Locked` and the stream is
  /// closed immediately; [`Self::shutdown`] also closes an active stream.
  /// Client protocol: end-of-stream, or an *increase* in the monotonic
  /// [`Self::dropped_lock_events`] counter since the client last read it,
  /// means cached lock state is stale — treat the vault as locked and
  /// resubscribe for a fresh snapshot (which resets nothing; compare
  /// against the newly read counter value from then on).
  Stream<LockEvent> lockEvents();

  Future<void> lockNow();

  Future<void> moveEntry({required String uuid, required String group});

  Future<void> moveGroup({required String uuid, required String parent});

  Future<void> purgeEntry({required String uuid});

  Future<VaultSummary> registerExistingVault({
    required String name,
    required String kdbxPath,
    KeyfileRef? keyfile,
  });

  Future<void> removeAttachment({required String uuid, required String key});

  Future<void> renameGroup({required String uuid, required String name});

  void reportActivity();

  void reportLifecycleState({required LifecycleStateDto state});

  Future<String> revealField({
    required String uuid,
    required RevealField field,
  });

  Future<void> saveAttachmentTo({
    required String uuid,
    required String key,
    required String destPath,
  });

  Future<List<SearchHit>> search({required SearchOptionsDto opts});

  Future<void> setExpiration({
    required String uuid,
    required PlatformInt64 epochSecs,
  });

  /// Persist UI preferences to the state directory.
  Future<void> setPrefs({required UiPrefs prefs});

  Future<void> shutdown();

  Future<List<String>> startupWarnings();

  Stream<SyncEvent> syncEvents();

  /// Run a sync cycle using the three-phase protocol.
  ///
  /// Phase 1 (short guard): validate, resolve vault name, clone
  ///   credentials, move vault + registry out, set `syncing = true`.
  /// Phase 2 (no guard): run `Sync::sync_now` wrapped in
  ///   `catch_unwind`. The session mutex is NOT held across the
  ///   network round-trips.
  /// Phase 3 (short guard): if `lock_pending` was set during phase 2,
  ///   discard the returned vault + registry and credentials, lock
  ///   the session. On panic, also lock (vault may be corrupted).
  ///   On success, restore vault + registry and clear the TOTP cache
  ///   (sync may have merged changed OTP fields).
  ///
  /// # Panics
  ///
  /// Internal `expect` for state that was validated in the same
  /// critical section — unreachable in normal operation.
  Future<SyncOutcomeDto> syncNow();

  Future<SyncStatusDto> syncStatus();

  /// Compute the current TOTP code for a cached entry.
  ///
  /// This method reads the TOTP cache via a `RwLock` read guard and
  /// NEVER takes the session mutex (threading rule 3). The cache is
  /// populated by [`Self::entry_detail`] when the entry kind is TOTP.
  ///
  /// Returns `Err(Internal)` on cache miss — callers must open the
  /// entry detail before requesting TOTP codes.
  TotpCode totpNow({required String uuid});

  Future<VaultTree> unlock({
    required String name,
    required String masterPassword,
    KeyfileRef? keyfile,
  });

  Future<void> updateEntry({required String uuid, required EntryEditDto edit});

  Future<VaultTree> vaultTree();
}
