#!/usr/bin/env bash
# Start the pinned MinIO server binary without a container. This exists for
# macOS CI runners, where Docker is unavailable; local development continues
# to use start_minio.sh by default.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.minio-env"
STATE_FILE="${SCRIPT_DIR}/.minio-native-state"
ACCESS_KEY="hidlins-test"
SECRET_KEY="hidlins-test-secret"
REGION="us-east-1"
PORT="${HIDLINS_MINIO_PORT:-9000}"
BIND="${HIDLINS_MINIO_BIND:-127.0.0.1}"
HOST="${HIDLINS_MINIO_HOST:-$BIND}"
ENDPOINT="http://${HOST}:${PORT}"

command -v minio >/dev/null 2>&1 || {
	echo "start_minio_native.sh: pinned 'minio' binary not found on PATH" >&2
	exit 1
}
command -v mc >/dev/null 2>&1 || {
	echo "start_minio_native.sh: pinned 'mc' binary not found on PATH" >&2
	exit 1
}

if [ -f "$STATE_FILE" ]; then
	echo "start_minio_native.sh: native fixture state already exists; run 'make minio-native-down' first" >&2
	exit 1
fi

DATA_DIR="$(mktemp -d "${TMPDIR:-/tmp}/hidlins-minio-native.XXXXXX")"
LOG_FILE="${DATA_DIR}/minio.log"
MINIO_ROOT_USER="$ACCESS_KEY" MINIO_ROOT_PASSWORD="$SECRET_KEY" \
	minio server "$DATA_DIR" --address "${BIND}:${PORT}" >"$LOG_FILE" 2>&1 &
PID="$!"

cleanup_failed_start() {
	kill "$PID" >/dev/null 2>&1 || true
	wait "$PID" >/dev/null 2>&1 || true
	rm -rf -- "$DATA_DIR"
}
trap cleanup_failed_start ERR

echo -n "start_minio_native.sh: waiting for MinIO to become healthy"
ready=""
for _ in $(seq 1 60); do
	if curl -fsS -o /dev/null "${ENDPOINT}/minio/health/live" 2>/dev/null; then
		ready="yes"
		break
	fi
	echo -n "."
	sleep 1
done
echo
if [ -z "$ready" ]; then
	echo "start_minio_native.sh: MinIO did not become healthy within 60s" >&2
	tail -20 "$LOG_FILE" >&2 || true
	false
fi

cat >"$STATE_FILE" <<EOF
HIDLINS_MINIO_NATIVE_PID='$PID'
HIDLINS_MINIO_NATIVE_DATA='$DATA_DIR'
EOF
cat >"$ENV_FILE" <<EOF
# Generated by start_minio_native.sh.
export HIDLINS_MINIO_ENDPOINT="${ENDPOINT}"
export HIDLINS_MINIO_ACCESS_KEY="${ACCESS_KEY}"
export HIDLINS_MINIO_SECRET_KEY="${SECRET_KEY}"
export HIDLINS_MINIO_REGION="${REGION}"
export HIDLINS_MINIO_BUCKET="${HIDLINS_MINIO_BUCKET:-hidlins-app-integration}"
EOF

"${SCRIPT_DIR}/make_bucket.sh" "${HIDLINS_MINIO_BUCKET:-hidlins-app-integration}"
trap - ERR
echo "start_minio_native.sh: ready. endpoint=${ENDPOINT}"
